import { validationResult } from "express-validator";
import { GoogleGenerativeAI } from "@google/generative-ai";
import { extractTextFromFile } from "../utils/fileExtractor.js";
import pkg from "json5";
const { parse } = pkg;

// Initialize Gemini AI client
const genAI = new GoogleGenerativeAI(
  process.env.GEMINI_API_KEY || process.env.GOOGLE_API_KEY
);

const QUIZ_QUESTION_OPTIONS = [10, 20, 30];
const MAX_GENERATED_QUESTIONS = 30;

// In-memory storage 
const quizSessions = new Map();
const quizResults = new Map();

// Generate Quiz Questions from Uploaded Document

export const generateQuiz = async (req, res) => {
  try {
    if (!req.file) {
      return res.status(400).json({
        success: false,
        message: "No file uploaded",
      });
    }

    const apiKey = process.env.GEMINI_API_KEY || process.env.GOOGLE_API_KEY;
    if (!apiKey) {
      return res.status(500).json({
        success: false,
        message:
          "AI API key not configured. Please add GEMINI_API_KEY to your environment variables.",
      });
    }

    // Validate file type and size
    const maxSize = 10 * 1024 * 1024; // 10MB
    if (req.file.size > maxSize) {
      return res.status(400).json({
        success: false,
        message: "File size exceeds 10MB limit",
      });
    }

    const allowedTypes = [".pdf", ".docx", ".doc", ".pptx", ".ppt"];
    const fileExt = req.file.originalname.toLowerCase().match(/\.\w+$/)?.[0];
    if (!allowedTypes.includes(fileExt)) {
      return res.status(400).json({
        success: false,
        message: "Invalid file type. Please upload PDF, DOCX, or PPTX files.",
      });
    }

    //  Extract text from file
    const extractedText = await extractTextFromFile(req.file);

    if (!extractedText || extractedText.trim().length < 100) {
      return res.status(400).json({
        success: false,
        message:
          "Insufficient text content in the uploaded file. Please ensure the document contains readable text.",
      });
    }

    // Used latest Gemini model 
  const model = genAI.getGenerativeModel({ model: "gemini-2.5-flash" });



const prompt = `
You are an AI quiz generator. Based only on the following text, create exactly ${MAX_GENERATED_QUESTIONS} multiple-choice questions.

STRICT FORMAT:
Return output in a pure JSON array with this exact structure (no Markdown, no extra words, no explanations outside JSON):

[
  {
    "question": "Question text?",
    "options": ["Option A", "Option B", "Option C", "Option D"],
    "correctAnswer": 0,
    "explanation": "Short reason why this is correct"
  }
]

Rules:
- Exactly ${MAX_GENERATED_QUESTIONS} questions.
- Each question must have 4 options.
- correctAnswer is the index (0–3).
- No markdown formatting.
- No text outside the JSON array.

Document Content:
${extractedText.slice(0, 8000)}
`;

    //  Generate quiz questions from Gemini
    const result = await model.generateContent(prompt);
    const response = result.response;
    const aiResponse = response.text();

    if (!aiResponse) throw new Error("No response generated from AI");

    //  Clean & Parse JSON safely
    let questions;
try {
  // Clean code blocks & extra text
  let cleaned = aiResponse
    .replace(/```json/gi, "")
    .replace(/```/g, "")
    .replace(/^[^{[]+/, "") // remove any prefix before JSON
    .replace(/[^}\]]+$/, "") // remove any trailing text after JSON
    .trim();

  // Try normal JSON parse first
  try {
    questions = JSON.parse(cleaned);
  } catch (err) {
    // Try JSON5 fallback (handles trailing commas, comments, etc.)
    questions = parse(cleaned);
  }

  // Ensure it's an array
  if (!Array.isArray(questions) || questions.length === 0) {
    throw new Error("No valid questions generated by AI.");
  }
  if (questions.length < 10) {
    console.warn(`Only ${questions.length} questions generated`);
  }
} catch (err) {
  console.error("Failed to parse AI response:", err.message);
  throw new Error("Invalid JSON format returned by AI.");
}

    const formattedQuestions = questions.slice(0, MAX_GENERATED_QUESTIONS).map((q, i) => ({
      id: `q-${Date.now()}-${i}`,
      question: q.question || `Question ${i + 1}`,
      options:
        Array.isArray(q.options) && q.options.length === 4
          ? q.options
          : ["Option A", "Option B", "Option C", "Option D"],
      correctAnswer:
        typeof q.correctAnswer === "number"
          ? Math.max(0, Math.min(3, q.correctAnswer))
          : 0,
      explanation: q.explanation || "No explanation provided.",
    }));

    // Create quiz session
    const sessionId = `session-${Date.now()}-${Math.random()
      .toString(36)
      .slice(2, 9)}`;

    quizSessions.set(sessionId, {
      userId: req.user._id.toString(),
      fileName: req.file.originalname,
      fileSize: req.file.size,
      questions: formattedQuestions,
      createdAt: new Date().toISOString(),
    });

    return res.status(200).json({
      success: true,
      data: {
        sessionId,
        fileName: req.file.originalname,
        fileSize: req.file.size,
        totalQuestions: formattedQuestions.length,
        questions: formattedQuestions,
        message:
          "Quiz generated successfully! You can now select the number of questions to attempt.",
      },
    });
  } catch (error) {
    console.error("Generate quiz error:", error);

    // Handle common Gemini API errors
    if (error.message?.includes("not found") || error.status === 404) {
      return res.status(500).json({
        success: false,
        message:
          "Gemini model not found. Please update to gemini-1.5-flash or gemini-1.5-pro.",
      });
    }

    if (error.message?.includes("API key")) {
      return res.status(500).json({
        success: false,
        message: "AI API key missing or invalid.",
      });
    }

    if (error.message?.includes("quota") || error.message?.includes("limit")) {
      return res.status(429).json({
        success: false,
        message:
          "AI quota or rate limit exceeded. Please try again after some time.",
      });
    }

    return res.status(500).json({
      success: false,
      message:
        error.message ||
        "Failed to generate quiz questions. Please try again later.",
    });
  }
};



export const startQuiz = async (req, res) => {
  try {
    const { sessionId, numberOfQuestions } = req.body;

    if (!sessionId) {
      return res.status(400).json({
        success: false,
        message: 'Session ID is required'
      });
    }

    const session = quizSessions.get(sessionId);
    if (!session) {
      return res.status(404).json({
        success: false,
        message: 'Quiz session not found or expired'
      });
    }

    // Verify user owns this session
    if (session.userId !== req.user._id.toString()) {
      return res.status(403).json({
        success: false,
        message: 'Unauthorized access to quiz session'
      });
    }

    // Validate number of questions
    const available = session.questions.length;
    if (!QUIZ_QUESTION_OPTIONS.includes(numberOfQuestions)) {
      return res.status(400).json({
        success: false,
        message: `Number of questions must be ${QUIZ_QUESTION_OPTIONS.join(', ')}`,
      });
    }

    if (numberOfQuestions > available) {
      return res.status(400).json({
        success: false,
        message: `Only ${available} questions available for this quiz`,
      });
    }

    const selectedQuestions = session.questions.slice(0, numberOfQuestions).map(q => ({
      id: q.id,
      question: q.question,
      options: q.options
    }));

    res.status(200).json({
      success: true,
      data: {
        sessionId,
        fileName: session.fileName,
        questions: selectedQuestions,
        totalQuestions: selectedQuestions.length,
        timePerQuestion: 60
      }
    });

  } catch (error) {
    console.error('Start quiz error:', error);
    res.status(500).json({
      success: false,
      message: 'Failed to start quiz'
    });
  }
};

 //Submit Quiz and Calculate Results

export const submitQuiz = async (req, res) => {
  try {
    const errors = validationResult(req);
    if (!errors.isEmpty()) {
      return res.status(400).json({
        success: false,
        message: 'Validation failed',
        errors: errors.array()
      });
    }

    const { sessionId, answers, timeSpent } = req.body;

    if (!sessionId) {
      return res.status(400).json({
        success: false,
        message: 'Session ID is required'
      });
    }

    const session = quizSessions.get(sessionId);
    if (!session) {
      return res.status(404).json({
        success: false,
        message: 'Quiz session not found or expired'
      });
    }

    // Verify user owns this session
    if (session.userId !== req.user._id.toString()) {
      return res.status(403).json({
        success: false,
        message: 'Unauthorized access to quiz session'
      });
    }

    if (!Array.isArray(answers)) {
      return res.status(400).json({
        success: false,
        message: 'Answers must be an array'
      });
    }

    // Calculate results
    let correctCount = 0;
    const detailedAnswers = [];

    answers.forEach((userAnswer, index) => {
      const question = session.questions.find(q => q.id === userAnswer.questionId);
      if (question) {
        const isCorrect = userAnswer.selectedAnswer === question.correctAnswer;
        if (isCorrect) correctCount++;

        detailedAnswers.push({
          questionId: question.id,
          question: question.question,
          options: question.options,
          userAnswer: userAnswer.selectedAnswer,
          correctAnswer: question.correctAnswer,
          isCorrect,
          explanation: question.explanation
        });
      }
    });

    const totalQuestions = answers.length;
    const wrongCount = totalQuestions - correctCount;
    const percentage = Math.round((correctCount / totalQuestions) * 100);

    // Create result object
    const quizResult = {
      id: `result-${Date.now()}`,
      sessionId,
      userId: session.userId,
      fileName: session.fileName,
      totalQuestions,
      correctAnswers: correctCount,
      wrongAnswers: wrongCount,
      score: correctCount,
      percentage,
      timeSpent: timeSpent || 0,
      detailedAnswers,
      completedAt: new Date().toISOString()
    };

    // Store result
    const userId = session.userId;
    if (!quizResults.has(userId)) {
      quizResults.set(userId, []);
    }
    const userResults = quizResults.get(userId);
    userResults.push(quizResult);

    // Keep only last 100 results per user
    if (userResults.length > 100) {
      userResults.splice(0, userResults.length - 100);
    }

    res.status(200).json({
      success: true,
      message: 'Quiz submitted successfully',
      data: {
        resultId: quizResult.id,
        totalQuestions,
        correctAnswers: correctCount,
        wrongAnswers: wrongCount,
        percentage,
        timeSpent,
        detailedAnswers
      }
    });

  } catch (error) {
    console.error('Submit quiz error:', error);
    res.status(500).json({
      success: false,
      message: 'Failed to submit quiz'
    });
  }
};

 //Get Quiz Result by ID
 
export const getQuizResult = async (req, res) => {
  try {
    const { resultId } = req.params;
    const userId = req.user._id.toString();

    const userResults = quizResults.get(userId) || [];
    const result = userResults.find(r => r.id === resultId);

    if (!result) {
      return res.status(404).json({
        success: false,
        message: 'Quiz result not found'
      });
    }

    res.status(200).json({
      success: true,
      data: result
    });

  } catch (error) {
    console.error('Get quiz result error:', error);
    res.status(500).json({
      success: false,
      message: 'Failed to retrieve quiz result'
    });
  }
};

//Get User Quiz History

export const getUserQuizHistory = async (req, res) => {
  try {
    const userId = req.user._id.toString();
    const { limit = 20 } = req.query;

    const userResults = quizResults.get(userId) || [];

    // Sort by completion date (newest first) and limit results
    const sortedResults = userResults
      .sort((a, b) => new Date(b.completedAt) - new Date(a.completedAt))
      .slice(0, parseInt(limit))
      .map(result => ({
        id: result.id,
        fileName: result.fileName,
        totalQuestions: result.totalQuestions,
        correctAnswers: result.correctAnswers,
        wrongAnswers: result.wrongAnswers,
        percentage: result.percentage,
        timeSpent: result.timeSpent,
        completedAt: result.completedAt
      }));

    // Calculate statistics
    const totalQuizzes = userResults.length;
    const averageScore = totalQuizzes > 0
      ? Math.round(userResults.reduce((sum, result) => sum + result.percentage, 0) / totalQuizzes)
      : 0;

    const bestScore = totalQuizzes > 0
      ? Math.max(...userResults.map(result => result.percentage))
      : 0;

    res.status(200).json({
      success: true,
      data: {
        results: sortedResults,
        statistics: {
          totalQuizzes,
          averageScore,
          bestScore
        }
      }
    });

  } catch (error) {
    console.error('Get quiz history error:', error);
    res.status(500).json({
      success: false,
      message: 'Failed to retrieve quiz history'
    });
  }
};
